#!/usr/bin/env python3
"""Generate the bookshelf from books-en.json / books-fr.json, the single source.

Outputs (all committed, nothing runs on the server):
    books/index.html       the English shelf, static HTML (readable without JS)
    books/fr/index.html    the French shelf
    books/books-en.tex     the English reading guide (LaTeX)
    books/books-fr.tex     the French reading guide

Run it through ../generate-pdfs.sh, which also compiles the PDFs with tectonic.
To add a book: add an entry to both JSON files, put its cover in
assets/images/books/ (NN-name.jpg for the PDF, NN-name.webp for the web), run.
"""
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent


def load(lang: str) -> dict:
    return json.loads((ROOT / f"books-{lang}.json").read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------
def h(s: str) -> str:
    """Escape for HTML, turning *emphasis* into <i>."""
    return re.sub(r"\*(.+?)\*", r"<i>\1</i>", html.escape(s, quote=False))


def book_html(b: dict, page: dict, up: str) -> str:
    best = f'<p class="muted">{h(page["best_for"])}: {h(b["best_for"])}</p>' if b.get("best_for") else ""
    words = " ".join([b["title"], b["author"], b["tag"], b["note"], b["spark"]]).lower()
    return f'''          <li class="book" data-words="{html.escape(words)}">
            <img src="{up}assets/images/books/{b["cover"]}.webp" width="160" height="{b["cover_h"]}" loading="lazy" decoding="async" alt="">
            <div>
              <h3>{h(b["title"])}</h3>
              <p class="meta">{h(b["author"])}, {b["year"]}. {h(b["tag"])}</p>
              <p>{h(b["note"])}</p>
              {best}
              <p class="spark">{h(b["spark"])}</p>
            </div>
          </li>'''


def shelf_html(d: dict, other: dict) -> str:
    lang, p, g = d["lang"], d["page"], d["guide"]
    up = "../" if lang == "en" else "../../"
    here = "https://promaa.tech/books/" + ("" if lang == "en" else "fr/")
    n = sum(len(s["books"]) for s in d["sections"])
    sections = "\n".join(
        f'''      <section aria-labelledby="s{i}">
        <h2 id="s{i}">{h(s["title"])}</h2>
        <ul class="plain shelf">
{chr(10).join(book_html(b, p, up) for b in s["books"])}
        </ul>
      </section>'''
        for i, s in enumerate(d["sections"], 1)
    )
    pdf = up + "assets/docs/" + ("books-recommendations-en.pdf" if lang == "en" else "livres-recommandes-fr.pdf")
    return f'''<!doctype html>
<!-- Generated by books/generate.py from books-{lang}.json. Edit the JSON, not this file. -->
<html lang="{lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{h(p["title"])}, Marc Duboc</title>
  <meta name="description" content="{html.escape(p["description"])}">
  <link rel="canonical" href="{here}">
  <link rel="alternate" hreflang="en" href="https://promaa.tech/books/">
  <link rel="alternate" hreflang="fr" href="https://promaa.tech/books/fr/">
  <link rel="alternate" hreflang="x-default" href="https://promaa.tech/books/">
  <meta name="theme-color" content="#f2f4f6" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#121210" media="(prefers-color-scheme: dark)">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{here}">
  <meta property="og:site_name" content="Marc Duboc">
  <meta property="og:title" content="{html.escape(p["title"])}">
  <meta property="og:description" content="{html.escape(p["description"])}">
  <meta property="og:image" content="https://promaa.tech/assets/images/og.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@proma__">
  <link rel="icon" href="{up}favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="{up}assets/images/apple-touch-icon.png">
  <link rel="preload" href="{up}assets/fonts/comic-shanns-mono.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="{up}assets/css/tokens.css">
  <link rel="stylesheet" href="{up}assets/css/site.css">
  <link rel="stylesheet" href="{up}assets/css/print.css" media="print">
  <noscript><style>[data-theme-toggle], [data-needs-js], [data-postmarks], .search {{ display: none !important; }}</style></noscript>
  <script>try{{var t=localStorage.getItem("theme");if(t)document.documentElement.dataset.theme=t}}catch(e){{}}</script>
  <script type="module" src="{up}assets/js/site.js"></script>
  <script type="module" src="{up}assets/js/books.js"></script>
  <script type="speculationrules">{{"prerender":[{{"where":{{"and":[{{"href_matches":"/*"}},{{"not":{{"href_matches":"*.pdf"}}}}]}},"eagerness":"moderate"}}]}}</script>
</head>
<body>
  <a class="skip" href="#shelf">{"Skip to the books" if lang == "en" else "Aller aux livres"}</a>
  <div class="page">
    <header class="top">
      <nav aria-label="{"Main" if lang == "en" else "Navigation"}">
        <ul class="plain nav">
          <li><a href="{up}">{"home" if lang == "en" else "accueil"}</a></li>
          <li><a href="{up}essays/">{"writing" if lang == "en" else "essais"}</a></li>
          <li><a href="./" aria-current="page">{"books" if lang == "en" else "livres"}</a></li>
          <li><a href="{p["other_href"]}" hreflang="{other["lang"]}" lang="{other["lang"]}">{h(p["other_lang"])}</a></li>
        </ul>
      </nav>
      <button class="pen" type="button" data-theme-toggle aria-pressed="false">{"dark" if lang == "en" else "sombre"}</button>
    </header>

    <main id="shelf">
      <h1>{h(p["title"])}</h1>
      <p class="intro">{h(p["intro"])}</p>
      <p class="muted">{h(p["signature"])}. <a href="{pdf}">{h(p["guide_label"])}</a></p>

      <form class="search" role="search">
        <label for="q">{h(p["search_label"])}</label>
        <input id="q" type="search" placeholder="{html.escape(p["search_placeholder"])}" autocomplete="off" spellcheck="false">
        <p class="muted small" aria-live="polite" data-count data-template="{html.escape(p["count"])}">{h(p["count"].format(n=n))}</p>
      </form>
      <p class="empty" hidden data-empty data-template="{html.escape(p["none"])}"></p>

{sections}
    </main>

    <footer class="foot">
      <span>{"Set in Comic Shanns Mono. No framework, no tracker, no cookie." if lang == "en" else "Composé en Comic Shanns Mono. Ni framework, ni traceur, ni cookie."}</span>
      <a href="#postmarks" data-postmarks>postmarks <span data-stamps>0/10</span></a>
    </footer>
  </div>
</body>
</html>
'''


# ---------------------------------------------------------------------------
# LaTeX
# ---------------------------------------------------------------------------
def esc(s: str) -> str:
    s = s.replace("\\", r"\textbackslash{}")
    for a, b in [("{", r"\{"), ("}", r"\}"), ("$", r"\$"), ("&", r"\&"), ("#", r"\#"), ("_", r"\_"),
                 ("%", r"\%"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return re.sub(r"\*(.+?)\*", r"\\textit{\1}", s)


PREAMBLE = r"""% !TEX program = xelatex
% Generated by books/generate.py from books-LANGCODE.json. Edit the JSON, not this file.
\documentclass[9pt]{extarticle}
\usepackage[a4paper,top=14mm,bottom=14mm,left=15mm,right=15mm,footskip=8mm]{geometry}
\usepackage{xcolor}
\usepackage{fontspec}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{longtable}
\usepackage{array}
\usepackage{polyglossia}
\setmainlanguage{LANG}

% ---------- airmail: blue ink, red for what matters (tokens.css) ----------
\definecolor{ink}{HTML}{114678}
\definecolor{inkmuted}{HTML}{495057}
\definecolor{accent}{HTML}{C92A2A}
\definecolor{rule}{HTML}{CED4DA}
\color{ink}

% ---------- one family, one weight: Comic Shanns Mono ----------
\setmainfont{ComicShannsMono-Regular.ttf}[Path=../assets/fonts/, BoldFont=ComicShannsMono-Regular.ttf, ItalicFont=ComicShannsMono-Regular.ttf, ItalicFeatures={FakeSlant=0.15}]

\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot[R]{\footnotesize\color{inkmuted}\thepage}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}
\emergencystretch=3em
\graphicspath{{../assets/images/books/}}

\newcolumntype{L}{>{\raggedright\arraybackslash}p{87mm}}
\setlength{\tabcolsep}{0pt}
\setlength{\LTleft}{0pt}
\setlength{\LTright}{0pt}

\newcommand{\trackheader}[1]{{\large\color{accent}#1}}

% cover, title, author (year), tag, best-for line, note, spark
\NewDocumentCommand{\bookentry}{ +m +m +m +m +m +m +m }{%
  \begin{minipage}[t]{11mm}\vspace{0pt}\includegraphics[width=11mm]{#1}\end{minipage}\hspace{3mm}%
  \begin{minipage}[t]{\dimexpr\linewidth-14mm-4mm\relax}\vspace{0pt}
    \raggedright
    {\color{accent}#2}\par\vspace{0.8mm}
    {\footnotesize\color{inkmuted}#3. #4}\par\vspace{1mm}
    #5{\small #6}\par\vspace{1mm}
    {\small\color{inkmuted}\textcolor{accent}{$\rightarrow$} #7}\par
  \end{minipage}%
  \par\vspace{2pt}\textcolor{rule}{\rule{\dimexpr\linewidth-4mm\relax}{0.4pt}}%
}

\begin{document}
{\footnotesize\color{inkmuted}TAG\hfill LOCATION}\par\vspace{5mm}
{\huge\color{accent}TITLE}\par\vspace{4mm}
{\small PROLOGUE}\par\vspace{2mm}
{\footnotesize\color{inkmuted}PROLOGUEAUTHOR}\par\vspace{5mm}

\begin{longtable}{@{}L@{\hspace{6mm}}L@{}}
ROWS
\end{longtable}

\vspace{4mm}
{\footnotesize\color{inkmuted}COLOPHONLEFT\hfill COLOPHONRIGHT}\par
\end{document}
"""


def tex_cell(b: dict, best_label: str) -> str:
    best = f"{{\\small\\color{{inkmuted}}{esc(best_label)}: {esc(b['best_for'])}}}\\par\\vspace{{1mm}}" if b.get("best_for") else ""
    args = [esc(b["cover"] + ".jpg"), esc(b["title"]), esc(f"{b['author']} ({b['year']})"), esc(b["tag"]), best, esc(b["note"]), esc(b["spark"])]
    return "\\bookentry{" + "}{".join(args) + "}"


def tex(d: dict) -> str:
    g, rows = d["guide"], []
    for s in d["sections"]:
        rows.append("\\multicolumn{2}{@{}p{\\textwidth}@{}}{\\trackheader{" + esc(s["title"]) + "}}\\\\*[2mm]")
        books = s["books"]
        for i in range(0, len(books), 2):
            pair = [tex_cell(b, d["page"]["best_for"]) for b in books[i:i + 2]]
            rows.append(" & ".join(pair + [""] * (2 - len(pair))) + r"\\[3mm]")
    out = PREAMBLE.replace("LANGCODE", d["lang"]).replace("LANG", "french" if d["lang"] == "fr" else "english")
    for k, v in [("TAG", g["masthead_tag"]), ("LOCATION", g["masthead_location"]), ("TITLE", g["masthead_title"]),
                 ("PROLOGUEAUTHOR", g["prologue_author"]), ("PROLOGUE", g["prologue"]),
                 ("COLOPHONLEFT", g["colophon_left"]), ("COLOPHONRIGHT", g["colophon_right"])]:
        out = out.replace(k, esc(v))
    return out.replace("ROWS", "\n".join(rows))


# ---------------------------------------------------------------------------
def main() -> None:
    from subprocess import check_output  # cover heights, so the shelf never shifts while images load
    data = {lang: load(lang) for lang in ("en", "fr")}
    for d in data.values():
        for s in d["sections"]:
            for b in s["books"]:
                f = ROOT.parent / "assets/images/books" / f"{b['cover']}.webp"
                b["cover_h"] = check_output(["identify", "-format", "%h", str(f)]).decode()
    for lang, other in (("en", "fr"), ("fr", "en")):
        d = data[lang]
        out = ROOT / ("index.html" if lang == "en" else "fr/index.html")
        out.parent.mkdir(exist_ok=True)
        out.write_text(shelf_html(d, data[other]), encoding="utf-8")
        (ROOT / f"books-{lang}.tex").write_text(tex(d), encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT.parent)} and books-{lang}.tex ({sum(len(s['books']) for s in d['sections'])} books)")


if __name__ == "__main__":
    main()
